name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install modules
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      uses: actions/checkout@v2

      - name: Install modules
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        run: tsc
